version: '3.8'

services:
  django_freelance_exchange:
    container_name: django_freelance_exchange
    build:
      context: .
      dockerfile: config/django/Dockerfile
    restart: on-failure
    networks:
      - demo
    expose:
      - 8001
    volumes:
      - ./freelance_exchange:/app/freelance_exchange:z
    depends_on:
      - db_freelance_exchange
      - redis
    links:
      - db_freelance_exchange
    environment:
      - DJANGO_SETTINGS_MODULE=freelance_exchange.settings

  nginxfreelanceexchange:
    container_name: nginx_freelance_exchange
    build: 
      context: .
      dockerfile: config/nginx/Dockerfile
    restart: on-failure
    networks:
      - demo
    ports:
      - 8080:80
    volumes:
      - ./freelance_exchange:/app/freelance_exchange:z
    links:
      - django_freelance_exchange

  db_freelance_exchange:
    container_name: db_freelance_exchange
    image: postgres:15
    networks:
      - demo
    expose:
      - 5432
    env_file:
      - freelance_exchange/.env
    volumes:
      - ./db:/var/lib/postgresql:z

  redis:
    image: redis:latest
    container_name: redis_container
    networks:
      - demo
    env_file:
      - freelance_exchange/.env
    expose:
      - 6379
    volumes:
      - ./redisdata:/data
      - ./config/redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped


  adminer:
    container_name: adminer
    image: adminer:4.8.1-standalone
    restart: on-failure
    networks:
      - demo
    ports:
      - '8081:8080'
    links:
      - 'db_freelance_exchange'


networks:
  demo:
    driver: bridge
    # external: true
