version: '3.8'

services:
  django_freelance_exchange:
    container_name: django_freelance_exchange
    build:
      context: .
      dockerfile: config/django/Dockerfile
    restart: on-failure
    networks:
      - demo
    expose:
      - 8001
    volumes:
      - ./freelance_exchange:/app/freelance_exchange:z
    depends_on:
      - db_freelance_exchange
    links:
      - db_freelance_exchange

  nginxfreelanceexchange:
    container_name: nginx_freelance_exchange
    build: 
      context: .
      dockerfile: config/nginx/Dockerfile
    restart: on-failure
    networks:
      - demo
    ports:
      - 8080:80
    volumes:
      - ./freelance_exchange:/app/freelance_exchange:z
    links:
      - django_freelance_exchange

  db_freelance_exchange:
    container_name: db_freelance_exchange
    image: postgres:15
    networks:
      - demo
    expose:
      - 5432
    env_file:
      - freelance_exchange/.env
    volumes:
      - ./db:/var/lib/postgresql:z

  adminer:
    container_name: adminer
    image: adminer:4.8.1-standalone
    restart: on-failure
    networks:
      - demo
    ports:
      - '8081:8080'
    links:
      - 'db_freelance_exchange'

networks:
  demo:
    driver: bridge
    # external: true
